#!/bin/sh

# Usage: $0
# create and populate the 'app' directory to be served

if ! [ -d "KingdomCreator" ]; then
   echo 'cloning KingdomCreator randomizer from github (requires internet)'
   git clone https://github.com/blakevanlan/KingdomCreator.git
fi

if ! [ -d 'app' ]; then
   echo 'creating directory "app" and linking files into it'
   mkdir --verbose app
   ( cd app || exit
     for i in ../KingdomCreator/docs/img                   \
              ../KingdomCreator/docs/rules                 \
              ../KingdomCreator/docs/*.css                 \
              ../KingdomCreator/docs/*.js                  \
              ../DominionIndex/KingdomCreator_html/*.html  \
              ../DominionIndex/*.html                      \
              ../DominionIndex/cgi-bin                     \
              ../DominionIndex/img_index                   \
              ../DominionIndex/res                         \
              ../games                                  ; do
         ln --verbose -s "$i"
     done
   )
fi


cd app || exit

if ! [ -f board.html ]; then
   echo 'creating an initial board'
   ../DominionIndex/mkboard.sh -2 >board.html

   # another (simpler) solution would be to just create a dummy board:
   # echo '<html><body><h1>No board has been generated yet.</h1></body></html>' \
   #      >> board.html
fi

if ! [ -f game-index.html ]; then
   echo 'creating game content pages'
   ../DominionIndex/mkgames.sh
fi

for i in games/*; do
   GAME="game-unofficial-$(basename "$i").html"
   if [ -f "$i/mkgame.sh" ] && ! [ -e "$GAME" ]; then
      "$i/mkgame.sh" > "$GAME"
   fi
done

if ! [ -f start.html ]; then
   echo 'creating the start.html starting page'
   ../DominionIndex/mkstart.sh > start.html
fi
